# Generated by Django 5.2.7 on 2026-01-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_food_name_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
    ]
