# Generated by Django 5.2.7 on 2026-01-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
